task: "nextqa_mc_test"
dataset_name: MC
test_split: test
output_type: generate_until
doc_to_visual: !function utils.nextqa_doc_to_visual
doc_to_text: !function utils.nextqa_doc_to_text_mc
doc_to_target: !function utils.nextqa_doc_to_target
process_results: !function utils.nextqa_mc_process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
include: _default_template_yaml
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question with A, B, C, D, or E."